### ISSUE TITLE
Homebrew Error

### ISSUE THREAD

**Issue by drewauff** [babarot/homebrew-tap#1]
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the b4b4r07/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/b4b4r07/homebrew-tap/Formula/gomi.rb:6

**Comment by kaisugi** [comment]
This is the same issue https://github.com/derailed/k9s/issues/1289
